[package]
name = "aur-thumbsup"
version = "0.3.0"
authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]
description = "A tool to manage voting for favorite AUR packages"
documentation = "https://github.com/bpetlert/aur-thumbsup"
homepage = "https://github.com/bpetlert/aur-thumbsup"
repository = "https://github.com/bpetlert/aur-thumbsup"
readme = "README.md"
license = "MIT"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3.13", default-features = true }
log = "0.4.8"
pretty_env_logger = "0.4.0"
anyhow = "1.0.28"
toml = "0.5.6"
reqwest = { version = "0.10.4", features = ["blocking", "cookies", "gzip", "json", "rustls-tls"] }
cookie = { version = "0.13.3", features = ["percent-encode"] }
time = { version = "0.2.9", features = ["std"] }
scraper = "0.11.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
dialoguer = "0.5.0"
lazy_static = "1.4.0"
colored = "1.9.3"

[dev-dependencies]
csv = "1.1.3"
tempfile = "3.1.0"
